server:
  port: 7035   

spring:
  profiles: dev_env
  application:
    name: orderservice
  zipkin:
    baseUrl: localhost:9411 
  sleuth:
    enabled: true
    
  kafka:
    bootstrap-servers: localhost:9095

token:
  key: abcd0987654321qwertyuio
  validity: 86400000
            
eureka:
  instance:
    ip-address: false
    lease-renewal-interval-in-seconds: 5
    metadata-map: 
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:7010/eureka/  

logging:
  file: /tmp/mslogs/orderservice.log 
  level:
    com.metamagic.ms: DEBUG
    
management:
    endpoints:
        web:
         exposure:
          include: info, health, metrics      
          
---
server:
  port: 7036   

spring:
  profiles: qa_env
  application:
    name: orderservice
  zipkin:
    baseUrl: localhost:9411 
  sleuth:
    enabled: true
    
  kafka:
    bootstrap-servers: localhost:9095

token:
  key: abcd0987654321qwertyuio
  validity: 86400000
            
eureka:
  instance:
    ip-address: false
    lease-renewal-interval-in-seconds: 5
    metadata-map: 
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:7011/eureka/  

logging:
  file: /tmp/mslogs/orderservice.log 
  level:
    com.metamagic.ms: DEBUG
    
management:
    endpoints:
        web:
         exposure:
          include: info, health, metrics                