
server:
  port: 7060 

spring:
  profiles: dev_env
  application:
    name: userauthlobaservice 
  zipkin:
    baseUrl: localhost:9411
  sleuth:
    sampler:
       percentage:50.0       
            
eureka:
  instance:
    ip-address: false
    lease-renewal-interval-in-seconds: 5
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:7010/eureka/  
      
      
productservice:
  ribbon: 
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule
    ServerListRefreshInterval : 5000

logging:
  file: /tmp/mslogs/userauthlobaservice.log 
  level:
    com.metamagic.ms: DEBUG

management:
    endpoints:
        web:
         exposure:
          include: info, health, metrics, hystrix.stream
          
          
---


server:
  port: 7061 

spring:
  profiles: qa_env
  application:
    name: userauthlobaservice 
  zipkin:
    baseUrl: localhost:9411 
  sleuth:
    sampler:
       percentage:50.0       
            
eureka:
  instance:
    ip-address: false
    lease-renewal-interval-in-seconds: 5
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:7011/eureka/  
      
      
productservice:
  ribbon: 
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule
    ServerListRefreshInterval : 5000

logging:
  file: /tmp/mslogs/userauthlobaservice.log 
  level:
    com.metamagic.ms: DEBUG

management:
    endpoints:
        web:
         exposure:
          include: info, health, metrics, hystrix.stream          